version: "3.8"

services:
  nginx-proxy:
    image: nginx:1.21
    container_name: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    links:
      - app
    depends_on:
      - app

  app:
    image: 984414310826.dkr.ecr.ap-northeast-1.amazonaws.com/decidim-git:staging-46452346
    container_name: app
    environment:
      NEW_RELIC_APP_NAME: decidim-app(staging)
    env_file:
      - .env

  sidekiq:
    image: 984414310826.dkr.ecr.ap-northeast-1.amazonaws.com/decidim-git:staging-46452346
    container_name: sidekiq
    command: bundle exec sidekiq -C /app/config/sidekiq.yml
    environment:
      NEW_RELIC_APP_NAME: decidim-sidekiq(staging)
    env_file:
      - .env
